import { ObjectId } from 'mongodb';

// Base interface for user data without MongoDB-specific fields
export interface IUserData {
  email: string;
  name?: string;
}

// Interface for creating a new user
export interface ICreateUser extends IUserData {
  createdAt: Date;
  updatedAt: Date;
}

// Full user interface including MongoDB fields
export interface IUser extends ICreateUser {
  _id?: ObjectId; // Optional because it's generated by MongoDB
}

// Optional: Add validation functions
export const validateUser = (data: Partial<IUserData>) => {
  const errors: string[] = [];

  if (data.email !== undefined) {
    if (!data.email) {
      errors.push('Email is required');
    } else if (!isValidEmail(data.email)) {
      errors.push('Invalid email format');
    }
  }

  if (data.name !== undefined && data.name.length > 99) {
    errors.push('Name must be less than 100 characters');
  }

  return errors;
};

// Helper function for email validation
const isValidEmail = (email: string): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

// Optional: Add MongoDB collection configuration
export const USER_COLLECTION = 'users';

// Optional: Add MongoDB indexes configuration
export const USER_INDEXES = [
  { key: { email: 1 }, unique: true },
  { key: { createdAt: 1 } },
] as const;
