version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --bind_ip_all # Add this line to ensure MongoDB binds to all interfaces
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: incorrectpassword
      MONGO_INITDB_DATABASE: jafa
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
